# Generated by Django 3.2.12 on 2023-09-10 07:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_setting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(default='img/default.png', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='theme_color',
            field=colorfield.fields.ColorField(blank=True, default='#10284e', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(blank=True, default='MyApp ', max_length=200),
        ),
    ]
