# Generated by Django 3.2.12 on 2023-09-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20230910_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(default='static/img/default.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
